FROM node:22-alpine AS build
WORKDIR /app

COPY ./package.json .

RUN yarn

RUN npm install --force

COPY . .

COPY .env.production .env

CMD [ "yarn", "start" ]


# FROM nginx:stable-alpine AS production
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 3000
# CMD ["nginx", "-g", "daemon off;"]