FROM node:alpine AS build
WORKDIR /app

COPY ./package.json .

RUN npm install 

COPY . .

ENV WATCHPACK_POLLING=true

COPY .env.production .env

CMD [ "npm", "start" ]


# FROM nginx:stable-alpine AS production
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 3000
# CMD ["nginx", "-g", "daemon off;"]