services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/dockerfile
    volumes:
      - ./backend/sqlite.db:/app/sqlite.db
      - ./backend/.env:/app/.env
    ports:
      - "8000:8000"

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: .
  #     dockerfile: frontend/dockerfile
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "80:3000"