# Dockerfile
FROM python:3.13-slim

WORKDIR /app 

COPY ./backend/requirements.txt .

RUN pip install --upgrade pip 

RUN pip install -r requirements.txt

COPY ./backend .

RUN python3 ./backend/init.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

EXPOSE 8000