# Dockerfile
FROM python:3.13-slim

WORKDIR /app 

COPY . /app 

RUN pip install --upgrade pip 

RUN apt-get update && apt-get install -y \
    build-essential \
    mariadb-client \
    libmariadb-dev \
    gcc 

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]