"""empty message

Revision ID: eed3c8d55188
Revises: 148f9a2459ab
Create Date: 2025-02-14 22:54:17.569328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed3c8d55188'
down_revision: Union[str, None] = '148f9a2459ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaches', sa.Column('objective', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teaches', 'objective')
    # ### end Alembic commands ###
