name: CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Set environment variable 
        run: | 
          echo "SQLALCHEMY_ASYNC_DATABASE_URL=${{ secrets.SQLALCHEMY_ASYNC_DATABASE_URL }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd backend
          pytest
  
  deploy:
    needs: test
    if: success()
    runs-on: ubuntu-22.04

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 140.245.75.185 >> ~/.ssh/known_hosts
      
      - name: Docker-compose Deploy
        run: |
          ssh ubuntu@140.245.75.185 << 'EOF'
            cd cheese
            git pull origin main
            docker-compose up --build -d
          EOF